pipeline{
  agent {
    docker {
            image 'openjdk:8-jdk' // Replace with your Docker image containing JDK and other necessary tools
        }
  }
  stages{
    stage('Checkout'){
      steps{
        script {
                    checkout([$class: 'GitSCM',
                              branches: [[name: '*/master']],
                              userRemoteConfigs: [[url: 'https://github.com/Sanjib8830/Jenkins-Zero-To-Hero.git']],
                              extensions: [[$class: 'PathRestriction', excludedPaths: '', includedPaths: 'HelloWorld.java']]])
                }
      }
    }
    stage('build'){
      steps{
        // Compile the Java program
        sh 'javac HelloWorld.java'
      }
    }
    stage('run'){
      steps{
        sh 'java Helloworld'
      }
    }
  }
}
