pipeline{
  agent {
    docker {
            image 'openjdk:8-jdk' // Replace with your Docker image containing JDK and other necessary tools
        }
  }
  stages{
    stage('Checkout'){
      steps{
        script{
          checkout scm
        }
      }
    }
    stage('build'){
      steps{
        // Compile the Java program
        sh 'javac HelloWorld.java'
      }
    }
    stage('run'){
      steps{
        sh 'java Helloworld'
      }
    }
  }
}
